/*
Deployment script for PaycheckNew

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "PaycheckNew"
:setvar DefaultFilePrefix "PaycheckNew"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [dbo].[AnnualSalary]...';


GO
CREATE TABLE [dbo].[AnnualSalary] (
    [SalaryId]   UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL,
    [EmployeeId] UNIQUEIDENTIFIER NOT NULL,
    [Amount]     DECIMAL (9, 2)   NOT NULL,
    [BeginDate]  SMALLDATETIME    NOT NULL,
    [EndDate]    SMALLDATETIME    NULL,
    CONSTRAINT [PK_Salary] PRIMARY KEY CLUSTERED ([SalaryId] ASC)
);


GO
PRINT N'Creating [dbo].[AvailableEmployeeDeduction]...';


GO
CREATE TABLE [dbo].[AvailableEmployeeDeduction] (
    [EmployeeId]      UNIQUEIDENTIFIER NOT NULL,
    [DeductionTypeId] INT              NOT NULL,
    [StartDate]       SMALLDATETIME    NOT NULL,
    [EndDate]         SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_AvailableEmployeeDeduction] PRIMARY KEY CLUSTERED ([EmployeeId] ASC, [DeductionTypeId] ASC, [StartDate] ASC, [EndDate] ASC)
);


GO
PRINT N'Creating [dbo].[Deduction]...';


GO
CREATE TABLE [dbo].[Deduction] (
    [DeductionId] UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL,
    [PaymentId]   UNIQUEIDENTIFIER NOT NULL,
    [Amount]      DECIMAL (6, 2)   NOT NULL,
    [Type]        VARCHAR (50)     NOT NULL,
    CONSTRAINT [PK_Deduction] PRIMARY KEY CLUSTERED ([DeductionId] ASC)
);


GO
PRINT N'Creating [dbo].[DeductionRate]...';


GO
CREATE TABLE [dbo].[DeductionRate] (
    [DeductionRateId] UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL,
    [DeductionTypeId] INT              NOT NULL,
    [Amount]          DECIMAL (7, 2)   NOT NULL,
    [StartDate]       SMALLDATETIME    NOT NULL,
    [EndDate]         SMALLDATETIME    NOT NULL
);


GO
PRINT N'Creating [dbo].[DeductionType]...';


GO
CREATE TABLE [dbo].[DeductionType] (
    [TypeId]      INT          IDENTITY (1, 1) NOT NULL,
    [Description] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_DeductionType] PRIMARY KEY CLUSTERED ([TypeId] ASC)
);


GO
PRINT N'Creating [dbo].[Employee]...';


GO
CREATE TABLE [dbo].[Employee] (
    [EmployeeId] UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL,
    [FirstName]  VARCHAR (50)     NOT NULL,
    [LastName]   VARCHAR (50)     NOT NULL,
    [HireDate]   DATE             NULL,
    [Active]     BIT              NOT NULL,
    CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED ([EmployeeId] ASC)
);


GO
PRINT N'Creating [dbo].[Payment]...';


GO
CREATE TABLE [dbo].[Payment] (
    [PaymentId]       UNIQUEIDENTIFIER NOT NULL,
    [EmployeeId]      UNIQUEIDENTIFIER NOT NULL,
    [Paydate]         DATE             NOT NULL,
    [TotalAmount]     DECIMAL (7, 2)   NOT NULL,
    [TotalDeductions] DECIMAL (6, 2)   NOT NULL,
    [TotalTaxes]      DECIMAL (6, 2)   NOT NULL,
    CONSTRAINT [PK_Payment] PRIMARY KEY CLUSTERED ([PaymentId] ASC)
);


GO
PRINT N'Creating [dbo].[Tax]...';


GO
CREATE TABLE [dbo].[Tax] (
    [TaxId]     UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL,
    [PaymentId] UNIQUEIDENTIFIER NOT NULL,
    [Amount]    DECIMAL (6, 2)   NOT NULL,
    [Type]      VARCHAR (50)     NOT NULL,
    CONSTRAINT [PK_Tax] PRIMARY KEY CLUSTERED ([TaxId] ASC)
);


GO
PRINT N'Creating [dbo].[TaxRate]...';


GO
CREATE TABLE [dbo].[TaxRate] (
    [TaxRateId]     UNIQUEIDENTIFIER NOT NULL,
    [TaxTypeId]     INT              NOT NULL,
    [Rate]          DECIMAL (4, 3)   NOT NULL,
    [StartDate]     SMALLDATETIME    NOT NULL,
    [EndDate]       SMALLDATETIME    NOT NULL,
    [MinimumSalary] DECIMAL (9, 2)   NULL,
    [MaximumSalary] DECIMAL (9, 2)   NULL,
    CONSTRAINT [PK_TaxRate] PRIMARY KEY CLUSTERED ([TaxRateId] ASC)
);


GO
PRINT N'Creating [dbo].[TaxType]...';


GO
CREATE TABLE [dbo].[TaxType] (
    [TaxTypeId]   INT          NOT NULL,
    [Description] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TaxType] PRIMARY KEY CLUSTERED ([TaxTypeId] ASC)
);


GO
PRINT N'Creating DF_Salary_SalaryId...';


GO
ALTER TABLE [dbo].[AnnualSalary]
    ADD CONSTRAINT [DF_Salary_SalaryId] DEFAULT (newid()) FOR [SalaryId];


GO
PRINT N'Creating DF_Deduction_DeductionId...';


GO
ALTER TABLE [dbo].[Deduction]
    ADD CONSTRAINT [DF_Deduction_DeductionId] DEFAULT (newid()) FOR [DeductionId];


GO
PRINT N'Creating DF_Deduction_Type...';


GO
ALTER TABLE [dbo].[Deduction]
    ADD CONSTRAINT [DF_Deduction_Type] DEFAULT ('Unknown') FOR [Type];


GO
PRINT N'Creating DF_DeductionRate_DeductionRateId...';


GO
ALTER TABLE [dbo].[DeductionRate]
    ADD CONSTRAINT [DF_DeductionRate_DeductionRateId] DEFAULT (newid()) FOR [DeductionRateId];


GO
PRINT N'Creating DF_Employee_EmployeeId...';


GO
ALTER TABLE [dbo].[Employee]
    ADD CONSTRAINT [DF_Employee_EmployeeId] DEFAULT (newid()) FOR [EmployeeId];


GO
PRINT N'Creating DF_Employee_Active...';


GO
ALTER TABLE [dbo].[Employee]
    ADD CONSTRAINT [DF_Employee_Active] DEFAULT ((1)) FOR [Active];


GO
PRINT N'Creating DF_Payment_TotalDeductions...';


GO
ALTER TABLE [dbo].[Payment]
    ADD CONSTRAINT [DF_Payment_TotalDeductions] DEFAULT ((0)) FOR [TotalDeductions];


GO
PRINT N'Creating DF_Payment_TotalTaxes...';


GO
ALTER TABLE [dbo].[Payment]
    ADD CONSTRAINT [DF_Payment_TotalTaxes] DEFAULT ((0)) FOR [TotalTaxes];


GO
PRINT N'Creating DF_Tax_TaxId...';


GO
ALTER TABLE [dbo].[Tax]
    ADD CONSTRAINT [DF_Tax_TaxId] DEFAULT (newid()) FOR [TaxId];


GO
PRINT N'Creating DF_Tax_Type...';


GO
ALTER TABLE [dbo].[Tax]
    ADD CONSTRAINT [DF_Tax_Type] DEFAULT ('Unknown') FOR [Type];


GO
PRINT N'Creating DF_TaxRate_TaxRateId...';


GO
ALTER TABLE [dbo].[TaxRate]
    ADD CONSTRAINT [DF_TaxRate_TaxRateId] DEFAULT (newid()) FOR [TaxRateId];


GO
PRINT N'Creating FK_AnnualSalary_Employee...';


GO
ALTER TABLE [dbo].[AnnualSalary] WITH NOCHECK
    ADD CONSTRAINT [FK_AnnualSalary_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[Employee] ([EmployeeId]);


GO
PRINT N'Creating FK_AvailableEmployeeDeduction_AvailableEmployeeDeduction...';


GO
ALTER TABLE [dbo].[AvailableEmployeeDeduction] WITH NOCHECK
    ADD CONSTRAINT [FK_AvailableEmployeeDeduction_AvailableEmployeeDeduction] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[Employee] ([EmployeeId]);


GO
PRINT N'Creating FK_AvailableEmployeeDeduction_DeductionType...';


GO
ALTER TABLE [dbo].[AvailableEmployeeDeduction] WITH NOCHECK
    ADD CONSTRAINT [FK_AvailableEmployeeDeduction_DeductionType] FOREIGN KEY ([DeductionTypeId]) REFERENCES [dbo].[DeductionType] ([TypeId]);


GO
PRINT N'Creating FK_Deduction_Payment...';


GO
ALTER TABLE [dbo].[Deduction] WITH NOCHECK
    ADD CONSTRAINT [FK_Deduction_Payment] FOREIGN KEY ([PaymentId]) REFERENCES [dbo].[Payment] ([PaymentId]);


GO
PRINT N'Creating FK_DeductionRate_DeductionType...';


GO
ALTER TABLE [dbo].[DeductionRate] WITH NOCHECK
    ADD CONSTRAINT [FK_DeductionRate_DeductionType] FOREIGN KEY ([DeductionTypeId]) REFERENCES [dbo].[DeductionType] ([TypeId]);


GO
PRINT N'Creating FK_Payment_Employee...';


GO
ALTER TABLE [dbo].[Payment] WITH NOCHECK
    ADD CONSTRAINT [FK_Payment_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[Employee] ([EmployeeId]);


GO
PRINT N'Creating FK_Tax_Payment...';


GO
ALTER TABLE [dbo].[Tax] WITH NOCHECK
    ADD CONSTRAINT [FK_Tax_Payment] FOREIGN KEY ([PaymentId]) REFERENCES [dbo].[Payment] ([PaymentId]);


GO
PRINT N'Creating FK_TaxRate_TaxType...';


GO
ALTER TABLE [dbo].[TaxRate] WITH NOCHECK
    ADD CONSTRAINT [FK_TaxRate_TaxType] FOREIGN KEY ([TaxTypeId]) REFERENCES [dbo].[TaxType] ([TaxTypeId]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[AnnualSalary] WITH CHECK CHECK CONSTRAINT [FK_AnnualSalary_Employee];

ALTER TABLE [dbo].[AvailableEmployeeDeduction] WITH CHECK CHECK CONSTRAINT [FK_AvailableEmployeeDeduction_AvailableEmployeeDeduction];

ALTER TABLE [dbo].[AvailableEmployeeDeduction] WITH CHECK CHECK CONSTRAINT [FK_AvailableEmployeeDeduction_DeductionType];

ALTER TABLE [dbo].[Deduction] WITH CHECK CHECK CONSTRAINT [FK_Deduction_Payment];

ALTER TABLE [dbo].[DeductionRate] WITH CHECK CHECK CONSTRAINT [FK_DeductionRate_DeductionType];

ALTER TABLE [dbo].[Payment] WITH CHECK CHECK CONSTRAINT [FK_Payment_Employee];

ALTER TABLE [dbo].[Tax] WITH CHECK CHECK CONSTRAINT [FK_Tax_Payment];

ALTER TABLE [dbo].[TaxRate] WITH CHECK CHECK CONSTRAINT [FK_TaxRate_TaxType];


GO
PRINT N'Update complete.'
GO
